Fix error message for invalid_sc()

diff --git a/termux-url-opener b/termux-url-opener
--- a/termux-url-opener
+++ b/termux-url-opener
@@ -99,7 +99,7 @@ print_msg()
 
 invalid_sc()
 {
-    echo "invalid command: '${1}'" >&2
+    echo "invalid shortcut: '${1}'" >&2
 }
 
 pause()
